ALTER PROCEDURE SP_D_FUN_FUNCIONARIO
@REGISTRO CHAR(14) AS
SET NOCOUNT ON
DECLARE @NR_FUNC INT
SELECT @NR_FUNC = COUNT(FUN_CH_REGISTRO) FROM FUN_FUNCIONARIO
WHERE FUN_CH_REGISTRO = @REGISTRO

IF @NR_FUNC = 0
BEGIN
	RAISERROR('Não é possível efetuar a exclusão. O funcionario não se encontra cadastrado no banco de dados',15,1)
	RETURN
END

DELETE FROM FUN_FUNCIONARIO WHERE FUN_CH_REGISTRO = @REGISTRO
RETURN
GO

EXEC SP_D_FUN_FUNCIONARIO '111111111112'