CREATE DATABASE FUNCIONARIOS;
GO
USE FUNCIONARIOS;

CREATE TABLE FUN_FUNCIONARIO(
FUN_IN_CODIGO INT NOT NULL IDENTITY CONSTRAINT FUN_PK_FUNCIONARIO PRIMARY KEY,
FUN_CH_REGISTRO CHAR(14) NOT NULL CONSTRAINT FUN_UK_FUN_REGISTRO UNIQUE
	CONSTRAINT FUN_CK_FUN_REGISTRO CHECK(FUN_CH_REGISTRO 
		LIKE ('[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]') 
			or FUN_CH_REGISTRO LIKE ('[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]')),
FUN_ST_NOME VARCHAR(70) NOT NULL,
FUN_ST_TIPO VARCHAR(50) NOT NULL,
FUN_DT_INCLUSAO DATE NOT NULL CONSTRAINT FUN_DF_FUN_INCLUSAO DEFAULT GETDATE(),
FUN_DT_DATAADMISSAO DATE NOT NULL,

FUN_RE_VALOR NUMERIC(12,2) NOT NULL CONSTRAINT FUN_DF_FUN_VALOR DEFAULT 0
		CONSTRAINT FUN_CK_FUN_VALOR CHECK (FUN_RE_VALOR >=0),
FUN_IN_NUMERO INT NOT NULL CONSTRAINT FUN_DF_FUN_NUMERO DEFAULT 0
		CONSTRAINT FUN_CK_FUN_NUMERO CHECK (FUN_IN_NUMERO >=0),
FUN_RE_SALARIO NUMERIC(12,2) NOT NULL CONSTRAINT FUN_DF_FUN_SALARIO DEFAULT 0
		CONSTRAINT FUN_CK_FUN_SALARIO CHECK (FUN_RE_SALARIO >=0),
)

select * from FUN_FUNCIONARIO







INSERT INTO FUN_FUNCIONARIO VALUES ('44444444444','joão lucas','mensalista','2020-05-05',1000,3)
select * from FUN_FUNCIONARIO