ALTER PROCEDURE SP_S_FUN_FUNCIONARIO_2 
@REGISTRO CHAR(14)
AS

SELECT 
	FUN_IN_CODIGO AS 'Código',
	FUN_CH_REGISTRO AS 'Registro',
	FUN_ST_NOME AS 'Nome',
	FUN_ST_TIPO AS 'Tipo',
	CONVERT(CHAR(10),FUN_DT_INCLUSAO,103) AS 'Data Inclusão',
	CONVERT(CHAR(10),FUN_DT_DATAADMISSAO,103) AS 'Data Admissão',
	DATEDIFF(MM, FUN_DT_DATAADMISSAO, GETDATE()) AS 'Tempo de Serviço em meses',
	FUN_RE_VALOR AS 'Valor Ganho por hr/sal. min ',
	FUN_IN_NUMERO AS 'Número de hr/sal. min',
	FUN_RE_SALARIO AS 'Salário'
FROM
	FUN_FUNCIONARIO WHERE FUN_CH_REGISTRO = @REGISTRO
RETURN

SP_S_FUN_FUNCIONARIO_2 11111111111   