ALTER PROCEDURE SP_U_FUN_FUNCIONARIO
@REGISTRO CHAR(14), @NOME VARCHAR(70), @TIPO VARCHAR(50), @DATAADMISSAO DATE, @VALOR NUMERIC(12,2), @NUMERO INT 
AS
SET NOCOUNT ON
DECLARE @NR_FUNC INT
--EFETUANDO O SELECT QUE IRÁ CONTAR O FUNCIONARIO E ATRIBUINDO NA VARIAVEL @NR_FUNC
SELECT @NR_FUNC = COUNT(FUN_CH_REGISTRO) FROM FUN_FUNCIONARIO
	WHERE FUN_CH_REGISTRO = @REGISTRO
--COMPARANDO SE O TOTAL DE FUNCIONARIO É MAIOR  QUE ZERO(OU SEJA, SE JÁ EXISTE NO BD)
IF @NR_FUNC = 0 
BEGIN
	RAISERROR('Não foi possível realizar a alteração! O funcionario não se encontra cadastrado no banco de dados!',15,1)
	RETURN
END

--COMPARANDO SE O VALOR É NEGATIVO
IF @VALOR <0
BEGIN
	RAISERROR('O valor de salario minimo ou por hora não pode ser negativo!',15,1)
	RETURN
END

--COMPARANDO SE O NUMERO É NEGATIVO
IF @VALOR <0
BEGIN
	RAISERROR('O número de horas trabalhadas ou de salarios minimos não pode ser negativo!',15,1)
	RETURN
END

--COMPARANDO O TAMANHO  DA STRING DOS CAMPOS REGISTRO, NOME E TIPO
IF (LEN(TRIM(@NOME)) = 0) OR (LEN(TRIM(@TIPO)) = 0) OR (LEN(TRIM(@REGISTRO)) <> 14) AND (LEN(TRIM(@REGISTRO)) <> 11)
BEGIN
	RAISERROR('O registo, nome e tipo são obrigatórios',15,1)
	RETURN
END

--VERIFICANDO O TIPO DO EMPREGADO É ACEITAVEL
IF (UPPER(@TIPO) <> UPPER('freelancer')) AND (UPPER(@TIPO) <> UPPER('mensalista'))
BEGIN
	RAISERROR('O tipo de empregado não é uma opção tente Freelancer ou Mensalista!',15,1)
	RETURN
END

UPDATE FUN_FUNCIONARIO SET FUN_CH_REGISTRO = @REGISTRO,
FUN_ST_NOME = @NOME,
FUN_ST_TIPO = UPPER(@TIPO),
FUN_DT_DATAADMISSAO = @DATAADMISSAO,
FUN_RE_VALOR = @VALOR,
FUN_IN_NUMERO = @NUMERO
WHERE FUN_CH_REGISTRO = @REGISTRO
GO

EXEC SP_U_FUN_FUNCIONARIO '11111111111','Pedro Enrique','Freelancer','2021-04-04',40,7 

SELECT  *	FROM FUN_FUNCIONARIO